name: Android Build
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: armory3d/armorpaint

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: android-actions/setup-android@v3

      - name: Generate Android project
        run: |
          cd paint
          chmod +x ../base/make
          ../base/make --target android

      - name: Build APK
        working-directory: paint/build/ArmorPaint
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: ArmorPaint-debug-apk
          path: 'paint/build/ArmorPaint/**/outputs/apk/debug/*.apk'
